import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-screen flex flex-col">
        <header className="p-4 border-b flex justify-between shrink-0 h-16">
          <h1 className="text-xl font-bold">Deck Builder</h1>
          <nav className = "flex gap-4">
            <Link href="/">Home</Link>
            <Link href="/Decks">Decks</Link>
            <Link href="/Card_List">Card List</Link>
          </nav>
        </header>

        <main className="flex-1 flex min-h-0">
          {children}
        </main>
      </body>
    </html>
  );
}